//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Expr()
    * f1 -> <EOF>
    */
   public void visit(Prog n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Abs() RApp()
    *       | Var() RApp()
    *       | Int()
    */
   public void visit(Expr n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <FN>
    * f1 -> "("
    * f2 -> RType()
    * f3 -> <VAR>
    * f4 -> RParam()
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> Expr()
    * f8 -> "}"
    */
   public void visit(Abs n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> ( "," RType() <VAR> RParam() )?
    */
   public void visit(RParam n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( "(" Expr() RArg() ")" RApp() )?
    */
   public void visit(RApp n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( "," Expr() RArg() )?
    */
   public void visit(RArg n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> TInt()
    * f1 -> ( <ARROW> RType() )?
    */
   public void visit(RType n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <VAR>
    */
   public void visit(Var n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <N>
    */
   public void visit(Int n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <TINT>
    */
   public void visit(TInt n) {
      n.f0.accept(this);
   }

}
