//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n);
   public R visit(NodeListOptional n);
   public R visit(NodeOptional n);
   public R visit(NodeSequence n);
   public R visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Expr()
    * f1 -> <EOF>
    */
   public R visit(Prog n);

   /**
    * f0 -> Abs() RApp()
    *       | Var() RApp()
    *       | Int()
    */
   public R visit(Expr n);

   /**
    * f0 -> <FN>
    * f1 -> "("
    * f2 -> RType()
    * f3 -> <VAR>
    * f4 -> RParam()
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> Expr()
    * f8 -> "}"
    */
   public R visit(Abs n);

   /**
    * f0 -> ( "," RType() <VAR> RParam() )?
    */
   public R visit(RParam n);

   /**
    * f0 -> ( "(" Expr() RArg() ")" RApp() )?
    */
   public R visit(RApp n);

   /**
    * f0 -> ( "," Expr() RArg() )?
    */
   public R visit(RArg n);

   /**
    * f0 -> TInt()
    * f1 -> ( <ARROW> RType() )?
    */
   public R visit(RType n);

   /**
    * f0 -> <VAR>
    */
   public R visit(Var n);

   /**
    * f0 -> <N>
    */
   public R visit(Int n);

   /**
    * f0 -> <TINT>
    */
   public R visit(TInt n);

}

