//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJVoidDepthFirst<A> implements GJVoidVisitor<A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
      }
   }

   public void visit(NodeOptional n, A argu) {
      if ( n.present() )
         n.node.accept(this,argu);
   }

   public void visit(NodeSequence n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeToken n, A argu) {}

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Expr()
    * f1 -> <EOF>
    */
   public void visit(Prog n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> Abs() RApp()
    *       | Var() RApp()
    *       | Int()
    */
   public void visit(Expr n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <FN>
    * f1 -> "("
    * f2 -> RType()
    * f3 -> <VAR>
    * f4 -> RParam()
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> Expr()
    * f8 -> "}"
    */
   public void visit(Abs n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
   }

   /**
    * f0 -> ( "," RType() <VAR> RParam() )?
    */
   public void visit(RParam n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> ( "(" Expr() RArg() ")" RApp() )?
    */
   public void visit(RApp n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> ( "," Expr() RArg() )?
    */
   public void visit(RArg n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> TInt()
    * f1 -> ( <ARROW> RType() )?
    */
   public void visit(RType n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> <VAR>
    */
   public void visit(Var n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <N>
    */
   public void visit(Int n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <TINT>
    */
   public void visit(TInt n, A argu) {
      n.f0.accept(this, argu);
   }

}
