//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Expr()
    * f1 -> <EOF>
    */
   public void visit(Prog n);

   /**
    * f0 -> Abs() RApp()
    *       | Var() RApp()
    *       | Int()
    */
   public void visit(Expr n);

   /**
    * f0 -> <FN>
    * f1 -> "("
    * f2 -> RType()
    * f3 -> <VAR>
    * f4 -> RParam()
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> Expr()
    * f8 -> "}"
    */
   public void visit(Abs n);

   /**
    * f0 -> ( "," RType() <VAR> RParam() )?
    */
   public void visit(RParam n);

   /**
    * f0 -> ( "(" Expr() RArg() ")" RApp() )?
    */
   public void visit(RApp n);

   /**
    * f0 -> ( "," Expr() RArg() )?
    */
   public void visit(RArg n);

   /**
    * f0 -> TInt()
    * f1 -> ( <ARROW> RType() )?
    */
   public void visit(RType n);

   /**
    * f0 -> <VAR>
    */
   public void visit(Var n);

   /**
    * f0 -> <N>
    */
   public void visit(Int n);

   /**
    * f0 -> <TINT>
    */
   public void visit(TInt n);

}

