/* Generated By:JavaCC: Do not edit this line. FnConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FnConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FN = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int LCURLY = 8;
  /** RegularExpression Id. */
  int RCURLY = 9;
  /** RegularExpression Id. */
  int TINT = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int ARROW = 12;
  /** RegularExpression Id. */
  int N = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"fn\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"int\"",
    "<VAR>",
    "\"->\"",
    "<N>",
    "\",\"",
  };

}
